/* ────────────────────────────────────────────────────────────────
   citations.ts – discrete array of sources keyed by position
   Each element only *needs* a title and URL, but feel free to
   expand with authors, dates, etc.  The important part is that
   the array length and order exactly match the numeric indices
   used in DatasetRiskFramework.jsx.
────────────────────────────────────────────────────────────────── */

export const oaicite = [
  /* 0  */ { title: "WHO calls for safe and ethical AI for health", url: "https://www.who.int/news/item/16-05-2023-who-calls-for-safe-and-ethical-ai-for-health" },
  /* 1  */ { title: "The METRIC-framework for assessing data quality for trustworthy AI in medicine: a systematic review", url: "https://www.nature.com/articles/s41746-024-01196-4" },
  /* 2  */ { title: "Human Research Protection Program – HIPAA / PHI guidance", url: "https://cphs.berkeley.edu/hipaa/hipaa18.html" },
  /* 3  */ { title: "Re-identification of anonymised MRI head images with publicly available software: investigation of the current risk to patient privacy", url: "https://pubmed.ncbi.nlm.nih.gov/39640939/" },
  /* 4  */ { title: "Re-identification of anonymised MRI head images …", url: "https://pubmed.ncbi.nlm.nih.gov/39640939/" },
  /* 5  */ { title: "The Big Data minefield as AI shapes the future of health care", url: "https://healthydebate.ca/2024/06/topic/big-data-minefield-ai-health-care/" },
  /* 6  */ { title: "Leaky Databases Expose over 45 Million Medical Images and Patient Data", url: "https://www.bitdefender.com/en-us/blog/hotforsecurity/leaky-databases-expose-over-45-million-medical-images-and-patient-data" },
  /* 7  */ { title: "Leaky Databases Expose over 45 Million Medical Images and Patient Data", url: "https://www.bitdefender.com/en-us/blog/hotforsecurity/leaky-databases-expose-over-45-million-medical-images-and-patient-data" },
  /* 8  */ { title: "Study: Attacks Can Manipulate Medical-Imaging-AI Outcomes", url: "https://www.bankinfosecurity.com/study-attacks-manipulate-medical-imaging-ai-outcomes-a-18131" },
  /* 9  */ { title: "WHO calls for safe and ethical AI for health", url: "https://www.who.int/news/item/16-05-2023-who-calls-for-safe-and-ethical-ai-for-health" },
  /* 10 */ { title: "The Big Data minefield as AI shapes the future of health care", url: "https://healthydebate.ca/2024/06/topic/big-data-minefield-ai-health-care/" },
  /* 11 */ { title: "WHO calls for safe and ethical AI for health", url: "https://www.who.int/news/item/16-05-2023-who-calls-for-safe-and-ethical-ai-for-health" },
  /* 12 */ { title: "AI can determine race from medical images", url: "https://www.nibib.nih.gov/news-events/newsroom/study-finds-artificial-intelligence-can-determine-race-medical-images" },
  /* 13 */ { title: "Skin-Tone Analysis for Representation (STAR-ED)", url: "https://www.nature.com/articles/s41746-023-00881-0" },
  /* 14 */ { title: "AI Shows Dermatology Educational Materials Often Lack Darker Skin Tones", url: "https://hai.stanford.edu/news/ai-shows-dermatology-educational-materials-often-lack-darker-skin-tones" },
  /* 15 */ { title: "Skin-Tone Analysis for Representation (STAR-ED)", url: "https://www.nature.com/articles/s41746-023-00881-0" },
  /* 16 */ { title: "Skin-Tone Analysis for Representation (STAR-ED)", url: "https://www.nature.com/articles/s41746-023-00881-0" },
  /* 17 */ { title: "Reporting gaps in FDA-approved AI medical devices", url: "https://www.nature.com/articles/s41746-024-01270-x" },
  /* 18 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 19 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 20 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 21 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 22 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 23 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 24 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 25 */ { title: "BEAMRAD – bias documentation tool for medical imaging datasets", url: "https://www.nature.com/articles/s41598-024-83218-5" },
  /* 26 */ { title: "BEAMRAD Figure 1", url: "https://www.nature.com/articles/s41598-024-83218-5/figures/1" },
  /* 27 */ { title: "1557 Final Rule Protects Against Bias in Health-Care Algorithms", url: "https://healthlaw.org/1557-final-rule-protects-against-bias-in-health-care-algorithms/" },
  /* 28 */ { title: "1557 Final Rule Protects Against Bias in Health-Care Algorithms", url: "https://healthlaw.org/1557-final-rule-protects-against-bias-in-health-care-algorithms/" },
  /* 29 */ { title: "Digital Personal Data Protection Act (DPDP) 2023 – Guide for Healthcare Leaders", url: "https://www.seqrite.com/blog/the-dpdp-act-2023-guide-for-healthcare-leaders/" },
  /* 30 */ { title: "GDPR fines & penalties overview", url: "https://gdpr-info.eu/issues/fines-penalties/" },
  /* 31 */ { title: "DPDP 2023 – Guide for Healthcare Leaders", url: "https://www.seqrite.com/blog/the-dpdp-act-2023-guide-for-healthcare-leaders/" },
  /* 32 */ { title: "DPDP 2023 – Guide for Healthcare Leaders", url: "https://www.seqrite.com/blog/the-dpdp-act-2023-guide-for-healthcare-leaders/" },
  /* 33 */ { title: "Pre-Conception and Pre-Natal Diagnostic Techniques (PC-PNDT) Act 1994", url: "https://byjus.com/free-ias-prep/pre-conception-and-pre-natal-diagnostic-techniques-prohibition-of-sex-selection-act-1994/" },
  /* 34 */ { title: "Regulation of Artificial Intelligence in Medicine (LinkedIn post)", url: "https://www.linkedin.com/pulse/regulation-artificial-intelligence-medicine-koshechkin-phd-alvfe" },
  /* 35 */ { title: "AI can determine race from medical images", url: "https://www.nibib.nih.gov/news-events/newsroom/study-finds-artificial-intelligence-can-determine-race-medical-images" },
  /* 36 */ { title: "The Big Data minefield as AI shapes the future of health care", url: "https://healthydebate.ca/2024/06/topic/big-data-minefield-ai-health-care/" },
  /* 37 */ { title: "Predicting sex from retinal fundus photographs using automated deep learning", url: "https://www.nature.com/articles/s41598-021-89743-x" },
  /* 38 */ { title: "Google AI calculates cardiovascular risk from retinal images", url: "https://syncedreview.com/2018/02/20/its-all-in-the-eyes-google-ai-calculates-cardiovascular-risk-from-retinal-images/" },
  /* 39 */ { title: "Google AI calculates cardiovascular risk from retinal images", url: "https://syncedreview.com/2018/02/20/its-all-in-the-eyes-google-ai-calculates-cardiovascular-risk-from-retinal-images/" },
  /* 40 */ { title: "PC-PNDT Act 1994", url: "https://byjus.com/free-ias-prep/pre-conception-and-pre-natal-diagnostic-techniques-prohibition-of-sex-selection-act-1994/" },
  /* 41 */ { title: "PC-PNDT Act 1994", url: "https://byjus.com/free-ias-prep/pre-conception-and-pre-natal-diagnostic-techniques-prohibition-of-sex-selection-act-1994/" },
  /* 42 */ { title: "The Big Data minefield as AI shapes the future of health care", url: "https://healthydebate.ca/2024/06/topic/big-data-minefield-ai-health-care/" },
  /* 43 */ { title: "Leaky Databases Expose over 45 Million Medical Images and Patient Data", url: "https://www.bitdefender.com/en-us/blog/hotforsecurity/leaky-databases-expose-over-45-million-medical-images-and-patient-data" },
  /* 44 */ { title: "Study: Attacks Can Manipulate Medical-Imaging-AI Outcomes", url: "https://www.bankinfosecurity.com/study-attacks-manipulate-medical-imaging-ai-outcomes-a-18131" },
  /* 45 */ { title: "The METRIC-framework for assessing data quality for trustworthy AI in medicine", url: "https://www.nature.com/articles/s41746-024-01196-4" },
  /* 46 */ { title: "Human Research Protection Program – HIPAA/PHI guidance", url: "https://cphs.berkeley.edu/hipaa/hipaa18.html" },
  /* 47 */ { title: "1557 Final Rule Protects Against Bias in Health-Care Algorithms", url: "https://healthlaw.org/1557-final-rule-protects-against-bias-in-health-care-algorithms/" },
  /* 48 */ { title: "Re-identification of anonymised MRI head images …", url: "https://pubmed.ncbi.nlm.nih.gov/39640939/" },
  /* 49 */ { title: "Predicting sex from retinal fundus photographs …", url: "https://www.nature.com/articles/s41598-021-89743-x" },
  /* 50 */ { title: "WHO calls for safe and ethical AI for health", url: "https://www.who.int/news/item/16-05-2023-who-calls-for-safe-and-ethical-ai-for-health" },
  /* 51 */ { title: "AI Shows Dermatology Educational Materials Often Lack Darker Skin Tones", url: "https://hai.stanford.edu/news/ai-shows-dermatology-educational-materials-often-lack-darker-skin-tones" },
  /* 52 */ { title: "Reporting gaps in FDA-approved AI medical devices", url: "https://www.nature.com/articles/s41746-024-01270-x" },
  /* 53 */ { title: "The Big Data minefield as AI shapes the future of health care", url: "https://healthydebate.ca/2024/06/topic/big-data-minefield-ai-health-care/" },
  /* 54 */ { title: "DPDP 2023 – Guide for Healthcare Leaders", url: "https://www.seqrite.com/blog/the-dpdp-act-2023-guide-for-healthcare-leaders/" },
  /* 55 */ { title: "GDPR fines & penalties overview", url: "https://gdpr-info.eu/issues/fines-penalties/" },
  /* 56 */ { title: "Study: Attacks Can Manipulate Medical-Imaging-AI Outcomes", url: "https://www.bankinfosecurity.com/study-attacks-manipulate-medical-imaging-ai-outcomes-a-18131" },
  /* 57 */ { title: "PC-PNDT Act 1994", url: "https://byjus.com/free-ias-prep/pre-conception-and-pre-natal-diagnostic-techniques-prohibition-of-sex-selection-act-1994/" },
  /* 58 */ { title: "AI can determine race from medical images", url: "https://www.nibib.nih.gov/news-events/newsroom/study-finds-artificial-intelligence-can-determine-race-medical-images" },
  /* 59 */ { title: "Re-identification of anonymised MRI head images …", url: "https://pubmed.ncbi.nlm.nih.gov/39640939/" },
  /* 60 */ { title: "GDPR fines & penalties overview", url: "https://gdpr-info.eu/issues/fines-penalties/" },
  /* 61 */ { title: "Leaky Databases Expose over 45 Million Medical Images and Patient Data", url: "https://www.bitdefender.com/en-us/blog/hotforsecurity/leaky-databases-expose-over-45-million-medical-images-and-patient-data" },
  /* 62 */ { title: "1557 Final Rule Protects Against Bias in Health-Care Algorithms", url: "https://healthlaw.org/1557-final-rule-protects-against-bias-in-health-care-algorithms/" }
];
